/**
 * Reads pre-generated city intros from public/data/city-intros.json.
 *
 * The intros are generated by scripts/_generate-city-intros.ts for the
 * top 100 cities by place count. Re-running the script + redeploying
 * refreshes the JSON.
 *
 * Why a JSON file rather than a DB table: the intros change roughly
 * monthly (when counts shift meaningfully) and are read by SSR on every
 * city page. A static import is faster than a DB round-trip and means
 * cache invalidation happens via the deploy, not via ISR drift.
 */
import { readFileSync } from 'fs'
import { join } from 'path'

interface CityIntroRecord {
  intro: string
  updated: string
}

let cache: Record<string, CityIntroRecord> | null = null

function load(): Record<string, CityIntroRecord> {
  if (cache) return cache
  try {
    const path = join(process.cwd(), 'public', 'data', 'city-intros.json')
    const raw = readFileSync(path, 'utf-8')
    cache = JSON.parse(raw) as Record<string, CityIntroRecord>
    return cache
  } catch {
    cache = {}
    return cache
  }
}

/**
 * Returns the pre-generated intro paragraph for a city, or null if we
 * haven't generated one for this city (only the top 100 cities are
 * covered today).
 */
export function getCityIntro(city: string, country: string): string | null {
  const data = load()
  const direct = data[`${city}|||${country}`]
  if (direct) return direct.intro
  return null
}
