/**
 * Vegan scene descriptions for countries and cities.
 * Used on /vegan-places/[country] and /vegan-places/[country]/[city] pages.
 */

export const COUNTRY_DESCRIPTIONS: Record<string, string> = {
  'Germany': 'Germany is one of Europe\'s most vegan-friendly countries, with Berlin widely regarded as the vegan capital of the world. From traditional dishes reimagined plant-based — like vegan currywurst and döner — to innovative fine dining, the German vegan scene is thriving. Most supermarkets carry extensive vegan ranges, and cities like Hamburg, Munich, and Leipzig have vibrant plant-based communities.',
  'United Kingdom': 'The UK has seen explosive growth in veganism, with Veganuary starting here and now a global movement. London leads with hundreds of fully vegan restaurants, from upscale dining to street food markets. Cities like Bristol, Brighton, and Manchester are also hotspots. Most UK restaurants now offer dedicated vegan menus, and the country boasts Europe\'s highest rate of vegan product launches.',
  'France': 'France\'s vegan scene has blossomed remarkably despite its meat-and-cheese traditions. Paris now has a thriving plant-based restaurant scene, from vegan patisseries to Michelin-quality dining. Lyon, Bordeaux, and Montpellier are catching up fast. French vegan cuisine often brings the country\'s culinary artistry to plant-based cooking, with beautiful presentations and rich flavors.',
  'Spain': 'Spain\'s vegan movement is growing rapidly, particularly in Barcelona and Madrid. The Mediterranean diet\'s emphasis on vegetables, legumes, and olive oil provides a natural foundation for plant-based eating. Many traditional tapas are already vegan, and dedicated vegan restaurants are popping up across the country. The Canary Islands and Valencia are also emerging vegan destinations.',
  'Netherlands': 'The Netherlands punches well above its weight in vegan dining. Amsterdam is a plant-based paradise with dozens of fully vegan restaurants, and Dutch cities like Utrecht, Rotterdam, and The Hague follow closely. The country is also a leader in plant-based food innovation, being home to major meat-alternative companies and a progressive food culture that embraces sustainability.',
  'Austria': 'Vienna has become one of Europe\'s most exciting vegan destinations, with a scene that blends Austrian culinary tradition with modern plant-based innovation. Vegan schnitzels, strudels, and café culture thrive here. Graz, Innsbruck, and Salzburg also offer excellent options. Austria\'s strong organic farming tradition means high-quality local produce in most vegan restaurants.',
  'Italy': 'Italy\'s vegan scene beautifully merges la cucina italiana with plant-based principles. Milan leads with contemporary vegan dining, while Rome, Florence, and Bologna offer traditional Italian dishes reimagined without animal products. Many Italian staples — pasta with marinara, bruschetta, focaccia — are naturally vegan, and the country\'s emphasis on fresh, seasonal ingredients shines in its plant-based offerings.',
  'Greece': 'Greek cuisine is naturally vegan-friendly thanks to its Orthodox fasting tradition, which has produced centuries of delicious plant-based recipes. Athens has a growing dedicated vegan scene, and islands like Crete and Santorini offer incredible local produce. Traditional dishes like fasolada, gigantes, briam, and horta are all plant-based classics that every visitor should try.',
  'Belgium': 'Belgium\'s vegan scene is flourishing, led by Ghent — which was the first city in the world to have an official weekly veggie day. Brussels, Antwerp, and Leuven also offer excellent plant-based dining. Belgian vegan cuisine ranges from creative takes on traditional dishes to international fusion, and the country\'s famous chocolate and waffle traditions now include impressive vegan versions.',
  'Poland': 'Poland has emerged as an unexpected vegan hotspot in Central Europe. Warsaw\'s vegan scene is remarkable for its affordability and variety, with vegan milk bars (bar mleczny) and modern restaurants alike. Kraków, Wrocław, and Gdańsk follow with their own thriving scenes. Traditional Polish pierogi and other comfort foods have been brilliantly adapted for vegan diners.',
  'Sweden': 'Sweden\'s progressive food culture embraces plant-based eating wholeheartedly. Stockholm, Gothenburg, and Malmö have excellent vegan options, and most Swedish restaurants offer substantial vegan menus. The country\'s focus on sustainability and "lagom" (balanced) living aligns naturally with plant-based choices. Swedish vegan cuisine often features Nordic ingredients like lingonberries, root vegetables, and foraged mushrooms.',
  'Czech Republic': 'Prague has quietly become one of Central Europe\'s best vegan cities, with affordable and creative plant-based restaurants throughout the old town and beyond. The Czech vegan scene draws on local culinary traditions — hearty stews, dumplings, and pastries — reimagined without animal products. Brno and other cities are following Prague\'s lead.',
  'Switzerland': 'Switzerland\'s vegan scene reflects the country\'s emphasis on quality and sustainability. Zurich leads with upscale vegan dining, while Bern, Basel, and Geneva offer diverse options. Swiss vegan cuisine often features locally sourced organic ingredients. Despite the country\'s cheese and chocolate fame, plant-based alternatives are widely available and of exceptional quality.',
  'Portugal': 'Lisbon has become one of Southern Europe\'s most exciting vegan destinations. The city\'s creative food scene has embraced plant-based cooking with enthusiasm, from traditional Portuguese flavors to international fusion. Porto and the Algarve region are catching up. Portugal\'s warm climate means abundant fresh produce year-round, and many traditional dishes are naturally plant-based.',
  'Finland': 'Finland\'s vegan scene is growing alongside the country\'s reputation for innovation and sustainability. Helsinki offers excellent plant-based options, from Nordic-inspired fine dining to casual cafés. Finnish vegan cuisine features unique Nordic ingredients like wild berries, mushrooms, and root vegetables. The country\'s school lunch programs now routinely include vegan options.',
  'Denmark': 'Copenhagen\'s food scene is world-renowned, and its vegan offerings are no exception. The city that gave the world New Nordic cuisine now applies those same principles to plant-based cooking. Danish vegan restaurants emphasize seasonal, local ingredients and beautiful presentation. Aarhus and other cities are following suit with their own plant-based scenes.',
  'Hungary': 'Budapest offers surprisingly excellent vegan dining at very affordable prices. The city\'s ruin bars and restaurants increasingly cater to plant-based diners, and dedicated vegan spots serve creative Hungarian-inspired cuisine. Traditional dishes like lángos and gulyás have been adapted for vegans, alongside international options.',
  'Norway': 'Norway\'s vegan scene is growing in Oslo and other cities, with a focus on sustainability that aligns with the country\'s environmental values. Norwegian vegan cuisine often features local and seasonal ingredients, with creative takes on Nordic flavors. Despite the country\'s fishing traditions, plant-based options are increasingly mainstream.',
  'Ireland': 'Dublin and other Irish cities are embracing veganism with enthusiasm. The country\'s farm-to-table tradition translates well to plant-based dining, with many restaurants highlighting local produce. Ireland\'s café culture has also adapted, with most coffee shops offering plant milks and vegan bakes.',
  'Croatia': 'Croatia\'s vegan scene is emerging, particularly in Zagreb and along the Dalmatian coast. Mediterranean influences mean plenty of naturally plant-based options, from grilled vegetables to olive oil-dressed salads. Dedicated vegan restaurants are growing in number.',
  'Romania': 'Romania\'s Orthodox fasting traditions mean that many traditional dishes are naturally vegan. Bucharest has a growing dedicated vegan scene, and traditional Romanian cuisine offers excellent plant-based options like zacuscă, fasole bătută, and sarmale de post.',
  'Slovakia': 'Bratislava and Košice have growing vegan scenes with affordable, creative plant-based restaurants. Slovak cuisine\'s hearty tradition of dumplings, stews, and pastries is being reimagined for vegan diners.',
  'Slovenia': 'Ljubljana, the green capital of Europe, has a thriving vegan scene. Slovenian cuisine draws on Mediterranean, Central European, and Balkan influences, all of which translate beautifully to plant-based cooking.',
  'Bulgaria': 'Sofia has a small but passionate vegan community with several dedicated restaurants. Bulgarian cuisine features many naturally vegan dishes, including shopska salad (without the cheese), bean stews, and grilled vegetables.',
  'Estonia': 'Tallinn offers a surprisingly good vegan scene for a small capital, with modern plant-based restaurants alongside traditional Estonian cuisine that includes naturally vegan options.',
  'Latvia': 'Riga\'s food scene is evolving to include more vegan options, with several dedicated plant-based restaurants and most mainstream restaurants offering vegan choices.',
  'Lithuania': 'Vilnius has a growing vegan community with dedicated restaurants and cafés. Lithuanian cuisine is adapting traditional dishes like šaltibarščiai and cepelinai for plant-based diners.',
  'Luxembourg': 'Luxembourg City offers quality vegan dining that reflects the country\'s multicultural character, with French, German, and international plant-based influences.',
  'Ukraine': 'Kyiv and Lviv have passionate vegan communities with creative plant-based restaurants that draw on Ukrainian culinary traditions. Traditional dishes like borscht and varenyky are often naturally vegan.',
}

export const CITY_DESCRIPTIONS: Record<string, string> = {
  'Berlin, Germany': 'Berlin is widely considered the vegan capital of the world. With over 100 fully vegan restaurants, the city offers everything from döner kebab shops to fine dining. Kreuzberg, Friedrichshain, and Neukölln are particularly rich in plant-based options. The city\'s international and alternative culture has made it a magnet for vegan innovation.',
  'London, United Kingdom': 'London\'s vegan scene is one of the most diverse on the planet. From Shoreditch\'s trendy plant-based cafés to Soho\'s vegan fine dining, the city offers thousands of options. Borough Market, Camden, and Brick Lane are excellent for vegan street food. Most London restaurants now offer dedicated vegan menus.',
  'Paris, France': 'Paris has transformed its vegan scene in recent years. The city now boasts vegan patisseries, fromageries, and bistros that bring French culinary excellence to plant-based cuisine. Le Marais, the 11th arrondissement, and Bastille are particularly good areas for vegan dining.',
  'Wien, Austria': 'Vienna\'s vegan scene is thriving within the city\'s famous café culture. Vegan sachertorte, schnitzels, and traditional Viennese pastries are all available. The city has dozens of fully vegan restaurants, plus nearly every traditional café now offers plant-based options.',
  'Amsterdam, Netherlands': 'Amsterdam is a vegan paradise with dozens of dedicated plant-based restaurants. The city\'s progressive culture embraces veganism fully, from food trucks to upscale dining. De Pijp, Jordaan, and the canal ring area are excellent for plant-based exploration.',
  'Barcelona, Spain': 'Barcelona combines Mediterranean cuisine with a vibrant vegan scene. The Gothic Quarter, El Born, and Gràcia neighborhoods are packed with plant-based options. Spanish tapas culture translates brilliantly to vegan dining, with patatas bravas, pan con tomate, and grilled vegetables leading the way.',
  'Madrid, Spain': 'Madrid\'s vegan scene has grown enormously, with Malasaña and Lavapiés neighborhoods leading the charge. From traditional Spanish cooking reimagined plant-based to international fusion, Madrid offers a rich variety of vegan dining experiences.',
  'Praha, Czech Republic': 'Prague is one of Central Europe\'s best-kept vegan secrets. The city offers dozens of fully plant-based restaurants at remarkably affordable prices. From traditional Czech cuisine to raw food cafés, Prague\'s vegan scene is diverse and welcoming.',
  'Hamburg, Germany': 'Hamburg\'s vegan scene centers around the Schanzenviertel and St. Pauli neighborhoods, with creative restaurants, cafés, and the famous vegan Portuguese tart shops. The city\'s cosmopolitan port culture brings diverse plant-based influences.',
  'München, Germany': 'Munich proves that Bavarian cuisine can go vegan. The city offers plant-based versions of traditional dishes alongside international vegan restaurants. Haidhausen, Glockenbach, and Maxvorstadt are the best neighborhoods for vegan dining.',
  'Milano, Italy': 'Milan leads Italy\'s vegan revolution with contemporary plant-based restaurants that apply Italian culinary artistry to vegan cuisine. The Navigli district and Brera neighborhood are particularly good for finding vegan gems.',
  'Warszawa, Poland': 'Warsaw is arguably the best-value vegan city in Europe. Plant-based restaurants are abundant and incredibly affordable, from modern vegan bistros to reimagined traditional Polish milk bars. The Praga and Mokotów districts are vegan hotspots.',
  'Αθήνα, Greece': 'Athens offers a wonderful blend of traditional Greek plant-based dishes and modern vegan restaurants. Many Greek classics — fava, giant beans, horta, and more — are naturally vegan, and the city\'s food scene is embracing dedicated plant-based dining.',
  'Zürich, Switzerland': 'Zurich has a sophisticated vegan dining scene, with the world\'s oldest vegetarian restaurant, Hiltl, serving since 1898. The city offers high-quality plant-based options across all price ranges, from casual lunch spots to upscale dining.',
  'Bruxelles - Brussel, Belgium': 'Brussels combines Belgian culinary tradition with a growing vegan scene. From plant-based waffles and chocolate to creative international cuisine, the EU capital has something for every vegan diner.',
  'Lisboa, Portugal': 'Lisbon has become a vegan hotspot, with creative plant-based restaurants popping up across the city. The combination of Portuguese culinary flair, fresh Atlantic produce, and affordable prices makes it an ideal vegan destination.',
  'København, Denmark': 'Copenhagen\'s world-class food scene extends to its vegan offerings. New Nordic cuisine principles — seasonal, local, sustainable — align perfectly with plant-based cooking. The city offers everything from casual plant-based cafés to innovative fine dining.',
}

export function getCountryDescription(country: string): string | null {
  return COUNTRY_DESCRIPTIONS[country] || null
}

export function getCityDescription(city: string, country: string): string | null {
  return CITY_DESCRIPTIONS[`${city}, ${country}`] || null
}
