import type { Metadata, Viewport } from "next";
import { Plus_Jakarta_Sans, Manrope } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
// NOTE: Leaflet + marker-cluster CSS moved to src/components/map/MapCssBoot.tsx
// so it only ships with map-using routes (/map, /place/[id], /vegan-places/.../...).
// Every other route previously shipped ~60-80 KB gz of unused CSS.
import ClientProviders from "@/components/providers/ClientProviders";
import AppShell from "@/components/layout/AppShell";
import GoogleAnalytics from "@/components/analytics/GoogleAnalytics";
import GoogleTagManager from "@/components/analytics/GoogleTagManager";
import PageViewTracker from "@/components/analytics/PageViewTracker";
import NavigationProgress from "@/components/layout/NavigationProgress";
import MaterialSymbolsSwap from "@/components/layout/MaterialSymbolsSwap";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-jakarta',
  weight: ['400', '500', '600', '700', '800'],
});

const manrope = Manrope({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-manrope',
  weight: ['400', '500', '600', '700'],
});

// Next.js 15 moved viewport out of metadata -- it's now its own export.
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
}

// Single source of truth for the homepage tagline. Used in title, meta
// description, OG, and the Organization JSON-LD so they cannot drift apart.
// Numbers reflect actual DB counts as of 2026-06 (~52K places, ~1,400 cities
// with 5+ places, ~160 countries) per the honesty-first copy rule. We say
// "1,400+ active cities" rather than "10,000+ cities" because most of those
// 10K "cities" have only 1-2 places each - not a directory people can use.
const SITE_TITLE = 'PlantsPack: Free Vegan Tools, Places & Travel Guides';
const SITE_DESCRIPTION =
  'Free vegan barcode scanner, baking calculator, menu translator, drinks lookup, and 52,000+ vegan and vegan-friendly places across 1,400+ cities in 160+ countries - 100% vegan spots clearly flagged. Ad-free, no tracking, community-built.';

export const metadata: Metadata = {
  title: SITE_TITLE,
  description: SITE_DESCRIPTION,
  metadataBase: new URL('https://www.plantspack.com'),
  manifest: '/manifest.json',
  // Favicon + Apple Touch Icon are auto-served by Next.js's file-based
  // metadata convention from src/app/icon.png (512×512) and
  // src/app/apple-icon.png (180×180). Both are the green silhouette on
  // transparent background — no white square wrapper.
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
  verification: {
    // Pinterest domain claim → renders <meta name="p:domain_verify" content="...">
    other: { 'p:domain_verify': 'c0934acbbf2430867bedf8648981989a' },
  },
  // openGraph.images and twitter.images are auto-supplied by Next.js's
  // file-based metadata convention from src/app/opengraph-image.tsx and
  // src/app/twitter-image.tsx. Those generators render the brand SVG +
  // wordmark live, so we don't have to maintain a static og-image.png.
  // Per-page metadata can still override (place / post / recipe pages
  // do, with their own hero photo).
  openGraph: {
    type: 'website',
    siteName: 'PlantsPack',
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    url: 'https://www.plantspack.com/',
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    site: '@plantspackX',
  },
  alternates: {
    canonical: 'https://www.plantspack.com',
    types: {
      // Auto-discovery: aggregators (Feedly, Inoreader, Mastodon feed bots)
      // and modern browsers find the RSS feed via this <link rel="alternate">
      // tag in <head>. Generated by /blog/feed.xml/route.ts.
      'application/rss+xml': 'https://www.plantspack.com/blog/feed.xml',
    },
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'PlantsPack',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/*
          Preconnect to the third-party origins on the critical path so the
          TLS handshake + DNS lookup for fonts, hero images, and place card
          images happens in parallel with the document download. Skip
          tile.openstreetmap.org on purpose — that origin is only needed
          after CityMap lazy-mounts; warming it would defeat the deferral.
        */}
        {/*
          Preconnect only for the two origins on the critical path of every
          first paint: Supabase storage (LCP city-hero image + place images)
          and Google Fonts gstatic (icon font). Was three preconnects;
          Lighthouse audit flagged >3 as too many. lh3.googleusercontent.com
          is demoted to dns-prefetch — only used for signed-in user avatars
          (never on guest first paint, never the LCP element).
        */}
        <link rel="preconnect" href="https://mfeelaqjbtnypoojhfjp.supabase.co" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="https://lh3.googleusercontent.com" />
        {/*
          Material Symbols Outlined: narrowed from the full variable axis
          range (opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200) to a
          single-weight subset. The full range made Google Fonts ship 7.9MB
          on first paint of the city directory page; this trims it to a
          static subset under 200KB while preserving every icon glyph
          we render across the app.
        */}
        {/*
          Defer the Material Symbols stylesheet so it doesn't block first
          paint. The print-media trick: browsers fetch print stylesheets
          at low priority and don't apply them to screen rendering until
          we flip media to "all" post-hydration. ~150ms render-block win
          on mobile.

          The swap runs from <MaterialSymbolsSwap/> in <body> via useEffect
          — doing it inline in <head> would mutate the DOM before React
          hydrates and trip a hydration mismatch on the <link>'s `media`
          attribute. <noscript> fallback restores blocking-load for users
          with JS disabled.
        */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght@400&display=swap"
          media="print"
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          {...({ id: 'msym-stylesheet' } as any)}
          crossOrigin="anonymous"
        />
        <noscript>
          {/* eslint-disable-next-line @next/next/no-css-tags */}
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght@400&display=swap"
            crossOrigin="anonymous"
          />
        </noscript>
        {/*
          Brand JSON-LD lives in <head> (not <body>) on purpose: when emitted
          inside <body> under React 19 streaming SSR, Next.js renders it once
          as a real <script> tag AND re-serializes it inside the Flight
          hydration payload, producing two identical application/ld+json
          blocks in the rendered DOM. Keeping it in <head> with a stable id
          gives exactly one tag and the cleanest signal to Google.
        */}
        <script
          id="ld-org-website"
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@graph': [
                {
                  '@type': 'Organization',
                  '@id': 'https://www.plantspack.com/#organization',
                  name: 'PlantsPack',
                  url: 'https://www.plantspack.com',
                  logo: 'https://www.plantspack.com/plantspack-logo-real.svg',
                  description:
                    'Independent, ad-free vegan discovery platform with free barcode scanner, baking calculator, menu translator, drinks lookup, plus 52,000+ vegan and vegan-friendly places across 1,400+ cities in 160+ countries - 100% vegan spots clearly flagged. No paid placements.',
                  slogan: 'Trusted vegan discovery and free tools, ad-free.',
                  sameAs: [
                    'https://x.com/plantspackX',
                    'https://www.instagram.com/plants.pack/',
                    'https://www.facebook.com/profile.php?id=61583784658664',
                    'https://www.wikidata.org/wiki/Q139742042',
                    'https://alternativeto.net/software/plantspack/',
                    'https://github.com/Cleareds/plantspack',
                  ],
                },
                // WebSite ties all pages to the brand identity and lets
                // Google build rich site-name + hierarchy in SERPs. The
                // SearchAction now points at /search?q=… — added once that
                // route went live in the search-overhaul work.
                {
                  '@type': 'WebSite',
                  '@id': 'https://www.plantspack.com/#website',
                  url: 'https://www.plantspack.com',
                  name: 'PlantsPack',
                  publisher: { '@id': 'https://www.plantspack.com/#organization' },
                  potentialAction: {
                    '@type': 'SearchAction',
                    target: {
                      '@type': 'EntryPoint',
                      urlTemplate: 'https://www.plantspack.com/search?q={search_term_string}',
                    },
                    'query-input': 'required name=search_term_string',
                  },
                },
              ],
            }),
          }}
        />
        {/*
          Google Consent Mode v2 bootstrap — MUST run before gtag.js loads.
          Sets all storage to "denied" by default (GDPR opt-in preserved), then
          synchronously restores "granted" from a returning visitor's stored
          choice so they get full cookie measurement on the very first ping.
          With analytics_storage denied, GA still sends *cookieless* pings that
          GA4 uses for behavioural/organic modeling — this is what recovers the
          traffic the old "load nothing until consent" gate was throwing away.
          send_page_view:false → the single page_view is sent by PageViewTracker
          (avoids the old config+tracker double-count). ~12 lines, no network,
          negligible cost on first paint. Production + real domain only.
        */}
        {process.env.NODE_ENV === 'production' && (
          <script
            id="ga-consent-bootstrap"
            dangerouslySetInnerHTML={{
              __html: `
                window.dataLayer=window.dataLayer||[];
                function gtag(){dataLayer.push(arguments);}
                window.gtag=gtag;
                gtag('consent','default',{ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied',analytics_storage:'denied',wait_for_update:500});
                try{var c=JSON.parse(localStorage.getItem('plantspack_cookie_consent')||'null');
                if(c&&c.analytics===true)gtag('consent','update',{analytics_storage:'granted'});
                if(c&&c.marketing===true)gtag('consent','update',{ad_storage:'granted',ad_user_data:'granted',ad_personalization:'granted'});}catch(e){}
                if(location.hostname==='www.plantspack.com'||location.hostname==='plantspack.com'){
                  gtag('js',new Date());
                  gtag('config','G-402EVF2GP0',{send_page_view:false,anonymize_ip:true});
                }
              `,
            }}
          />
        )}
      </head>
      <body className={`${jakarta.variable} ${manrope.variable} font-body antialiased bg-surface text-on-surface min-h-screen`}>
        {/*
          GTM noscript fallback — only renders + executes for visitors with
          JS disabled (every other browser ignores <noscript>). Zero perf
          cost in the JS path: the iframe is never instantiated.
        */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-MJG3ZGS6"
            height="0"
            width="0"
            style={{ display: 'none', visibility: 'hidden' }}
          />
        </noscript>
        <GoogleAnalytics />
        <GoogleTagManager />
        <NavigationProgress />
        <MaterialSymbolsSwap />
        <Suspense fallback={null}>
          <PageViewTracker />
        </Suspense>
        <ClientProviders>
          <AppShell>
            {children}
          </AppShell>
        </ClientProviders>
      </body>
    </html>
  );
}
