import type { Metadata, Viewport } from "next";
import { Plus_Jakarta_Sans, Manrope } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
// NOTE: Leaflet + marker-cluster CSS moved to src/components/map/MapCssBoot.tsx
// so it only ships with map-using routes (/map, /place/[id], /vegan-places/.../...).
// Every other route previously shipped ~60-80 KB gz of unused CSS.
import ClientProviders from "@/components/providers/ClientProviders";
import AppShell from "@/components/layout/AppShell";
import GoogleAnalytics from "@/components/analytics/GoogleAnalytics";
import PageViewTracker from "@/components/analytics/PageViewTracker";
import NavigationProgress from "@/components/layout/NavigationProgress";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-jakarta',
  weight: ['400', '500', '600', '700', '800'],
});

const manrope = Manrope({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-manrope',
  weight: ['400', '500', '600', '700'],
});

// Next.js 15 moved viewport out of metadata -- it's now its own export.
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
}

// Single source of truth for the homepage tagline. Used in title, meta
// description, OG, and the Organization JSON-LD so they cannot drift apart.
// Numbers reflect actual DB counts as of 2026-05 (~52K places, ~10K cities,
// ~163 countries) rounded down per the honesty-first copy rule.
const SITE_TITLE = 'PlantsPack — Vegan Places & City Rankings Worldwide';
const SITE_DESCRIPTION =
  '50,000+ vegan and vegan-friendly places across 10,000+ cities in 160+ countries. Compare cities by vegan-friendliness with community reviews and ratings. Free, ad-free.';

export const metadata: Metadata = {
  title: SITE_TITLE,
  description: SITE_DESCRIPTION,
  metadataBase: new URL('https://www.plantspack.com'),
  manifest: '/manifest.json',
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
  // openGraph.images and twitter.images are auto-supplied by Next.js's
  // file-based metadata convention from src/app/opengraph-image.tsx and
  // src/app/twitter-image.tsx. Those generators render the brand SVG +
  // wordmark live, so we don't have to maintain a static og-image.png.
  // Per-page metadata can still override (place / post / recipe pages
  // do, with their own hero photo).
  openGraph: {
    type: 'website',
    siteName: 'PlantsPack',
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    url: 'https://www.plantspack.com/',
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    site: '@plantspackX',
  },
  alternates: {
    canonical: 'https://www.plantspack.com',
    types: {
      // Auto-discovery: aggregators (Feedly, Inoreader, Mastodon feed bots)
      // and modern browsers find the RSS feed via this <link rel="alternate">
      // tag in <head>. Generated by /blog/feed.xml/route.ts.
      'application/rss+xml': 'https://www.plantspack.com/blog/feed.xml',
    },
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'PlantsPack',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/*
          Preconnect to the third-party origins on the critical path so the
          TLS handshake + DNS lookup for fonts, hero images, and place card
          images happens in parallel with the document download. Skip
          tile.openstreetmap.org on purpose — that origin is only needed
          after CityMap lazy-mounts; warming it would defeat the deferral.
        */}
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://mfeelaqjbtnypoojhfjp.supabase.co" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://lh3.googleusercontent.com" crossOrigin="anonymous" />
        {/*
          Material Symbols Outlined: narrowed from the full variable axis
          range (opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200) to a
          single-weight subset. The full range made Google Fonts ship 7.9MB
          on first paint of the city directory page; this trims it to a
          static subset under 200KB while preserving every icon glyph
          we render across the app.
        */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght@400&display=swap"
          crossOrigin="anonymous"
        />
        {/*
          Brand JSON-LD lives in <head> (not <body>) on purpose: when emitted
          inside <body> under React 19 streaming SSR, Next.js renders it once
          as a real <script> tag AND re-serializes it inside the Flight
          hydration payload, producing two identical application/ld+json
          blocks in the rendered DOM. Keeping it in <head> with a stable id
          gives exactly one tag and the cleanest signal to Google.
        */}
        <script
          id="ld-org-website"
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@graph': [
                {
                  '@type': 'Organization',
                  '@id': 'https://www.plantspack.com/#organization',
                  name: 'PlantsPack',
                  url: 'https://www.plantspack.com',
                  logo: 'https://www.plantspack.com/plantspack-logo-real.svg',
                  description:
                    'Community-funded vegan platform mapping 50,000+ vegan and vegan-friendly places across 10,000+ cities in 160+ countries. Free, ad-free.',
                  slogan: 'Vegan places and city rankings, free and ad-free.',
                  sameAs: [
                    'https://x.com/plantspackX',
                    'https://www.instagram.com/plants.pack/',
                    'https://www.facebook.com/profile.php?id=61583784658664',
                    'https://www.wikidata.org/wiki/Q139742042',
                    'https://alternativeto.net/software/plantspack/',
                    'https://github.com/Cleareds/plantspack',
                  ],
                },
                // WebSite ties all pages to the brand identity and lets
                // Google build rich site-name + hierarchy in SERPs. The
                // SearchAction now points at /search?q=… — added once that
                // route went live in the search-overhaul work.
                {
                  '@type': 'WebSite',
                  '@id': 'https://www.plantspack.com/#website',
                  url: 'https://www.plantspack.com',
                  name: 'PlantsPack',
                  publisher: { '@id': 'https://www.plantspack.com/#organization' },
                  potentialAction: {
                    '@type': 'SearchAction',
                    target: {
                      '@type': 'EntryPoint',
                      urlTemplate: 'https://www.plantspack.com/search?q={search_term_string}',
                    },
                    'query-input': 'required name=search_term_string',
                  },
                },
              ],
            }),
          }}
        />
      </head>
      <body className={`${jakarta.variable} ${manrope.variable} font-body antialiased bg-surface text-on-surface min-h-screen`}>
        <GoogleAnalytics />
        <NavigationProgress />
        <Suspense fallback={null}>
          <PageViewTracker />
        </Suspense>
        <ClientProviders>
          <AppShell>
            {children}
          </AppShell>
        </ClientProviders>
      </body>
    </html>
  );
}
