import { config } from 'dotenv'; config({ path: '.env.local' });
import { createClient } from '@supabase/supabase-js';
const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { autoRefreshToken: false, persistSession: false } });
async function main() {
  const total = await sb.from('places').select('*', { count: 'exact', head: true }).is('archived_at', null);
  const fv = await sb.from('places').select('*', { count: 'exact', head: true }).eq('vegan_level', 'fully_vegan').is('archived_at', null);
  const mv = await sb.from('places').select('*', { count: 'exact', head: true }).eq('vegan_level', 'mostly_vegan').is('archived_at', null);
  const vf = await sb.from('places').select('*', { count: 'exact', head: true }).eq('vegan_level', 'vegan_friendly').is('archived_at', null);
  const vo = await sb.from('places').select('*', { count: 'exact', head: true }).eq('vegan_level', 'vegan_options').is('archived_at', null);
  const withDesc = await sb.from('places').select('*', { count: 'exact', head: true }).is('archived_at', null).not('description', 'is', null).neq('description', '');
  const withImg = await sb.from('places').select('*', { count: 'exact', head: true }).is('archived_at', null).not('main_image_url', 'is', null);
  const withRatings = await sb.from('places').select('*', { count: 'exact', head: true }).is('archived_at', null).gt('review_count', 0);
  const archived = await sb.from('places').select('*', { count: 'exact', head: true }).not('archived_at', 'is', null);
  const staging = await sb.from('place_staging').select('*', { count: 'exact', head: true }).eq('status', 'pending');
  const users = await sb.from('users').select('*', { count: 'exact', head: true });
  const reviews = await sb.from('place_reviews').select('*', { count: 'exact', head: true }).is('deleted_at', null);
  const eat = await sb.from('places').select('*', { count: 'exact', head: true }).eq('category', 'eat').is('archived_at', null);
  const store = await sb.from('places').select('*', { count: 'exact', head: true }).eq('category', 'store').is('archived_at', null);
  const hotel = await sb.from('places').select('*', { count: 'exact', head: true }).eq('category', 'hotel').is('archived_at', null);
  const t = total.count || 0;
  console.log('\n=== DATABASE QUALITY SUMMARY ===\n');
  console.log('PLACES BY VEGAN LEVEL');
  console.log(`  fully_vegan:    ${fv.count?.toLocaleString().padStart(7)} (${((fv.count||0)/t*100).toFixed(1)}%)`);
  console.log(`  mostly_vegan:   ${mv.count?.toLocaleString().padStart(7)} (${((mv.count||0)/t*100).toFixed(1)}%)`);
  console.log(`  vegan_friendly: ${vf.count?.toLocaleString().padStart(7)} (${((vf.count||0)/t*100).toFixed(1)}%)`);
  console.log(`  vegan_options:  ${vo.count?.toLocaleString().padStart(7)} (${((vo.count||0)/t*100).toFixed(1)}%)`);
  console.log(`  TOTAL ACTIVE:   ${t.toLocaleString().padStart(7)}`);
  console.log(`  archived:       ${archived.count?.toLocaleString().padStart(7)}`);
  console.log('\nPLACES BY CATEGORY');
  console.log(`  eat:   ${eat.count?.toLocaleString()}`);
  console.log(`  store: ${store.count?.toLocaleString()}`);
  console.log(`  hotel: ${hotel.count?.toLocaleString()}`);
  console.log('\nDATA COMPLETENESS');
  console.log(`  with description: ${withDesc.count?.toLocaleString()} / ${t.toLocaleString()} (${((withDesc.count||0)/t*100).toFixed(1)}%)`);
  console.log(`  with main image:  ${withImg.count?.toLocaleString()} / ${t.toLocaleString()} (${((withImg.count||0)/t*100).toFixed(1)}%)`);
  console.log(`  with reviews:     ${withRatings.count?.toLocaleString()} / ${t.toLocaleString()} (${((withRatings.count||0)/t*100).toFixed(1)}%)`);
  console.log('\nPLATFORM');
  console.log(`  users:            ${users.count?.toLocaleString()}`);
  console.log(`  place reviews:    ${reviews.count?.toLocaleString()}`);
  console.log(`  staging pending:  ${staging.count?.toLocaleString()}`);
}
main().catch(console.error);
