import type { TravelGuide } from '../types'

export const germanyGuide: TravelGuide = {
  countrySlug: 'germany',
  countryName: 'Germany',
  metaTitle: 'How to eat vegan in Germany — phrasebook & dish guide | Plants Pack',
  metaDescription: 'Germany is one of the easiest countries in the world to eat vegan: Berlin is a world capital of vegan dining, and every supermarket stocks a huge V-Label range. A practical guide.',
  vegFriendliness: 5,
  vegFriendlinessNote: 'Outstanding. Germany has the highest density of vegan products in supermarkets globally and Berlin is one of the world capitals of vegan dining.',
  tldr: 'Germany is the easiest country in Europe to eat vegan, full stop. Berlin alone has hundreds of dedicated vegan restaurants, every major supermarket (Rewe, Edeka, Lidl, Aldi, Kaufland) carries a serious V-Label range, and "pflanzlich" (plant-based) labelling is reliable. The traditional Bavarian dish scene is the only place you need to plan, and even there a Kaufland is usually nearby.',
  intro: [
    'Berlin is genuinely one of the vegan capitals of the world. Brammibal\'s Donuts has multiple shops, Swing Kitchen does vegan schnitzel and burgers as a chain, Vincent Vegan runs the vegan döner and currywurst game, Katzentempel pairs cat cafes with a fully vegan menu, and Veganz operates 100% vegan supermarkets. Even neighbourhood kebab shops in Kreuzberg and Neukölln will do a vegan döner without blinking. Mustafa\'s Gemüse Kebap has long had a vegan option. The density of options means you basically never need to plan a meal in advance.',
    'The supermarket scene is the real differentiator. **Rewe, Edeka, Lidl, Aldi, and Kaufland** all carry deep vegan ranges marked with the **V-Label** (the European Vegetarian Union\'s seal, with separate vegan and vegetarian variants). Beyond Meat, Vivera, Like Meat, Garden Gourmet, and the **Rügenwalder Mühle** vegan line (a former meat brand that pivoted hard) are widely stocked. Oatly, Alpro, and supermarket-own oat/soy/almond milks are everywhere. Vegan cheese, vegan quark, vegan yogurt, vegan deli slices, vegan frozen pizzas - all in normal supermarkets at normal prices.',
    '**ProVeg International** (based in Berlin) and the European **V-Label** certification are the two trust signals worth recognising. The V-Label vegan logo on packaging is third-party audited and reliable - if it is on the pack, it is vegan. ProVeg also runs the V-Label scheme in Germany and pushes restaurant certification. Some chains and independent cafes carry V-Label menu items, which is the strongest restaurant-level signal you will find anywhere in Europe.',
    'Regional variation matters but is shrinking. Berlin, Hamburg, Munich, Frankfurt, Cologne, Leipzig, and Stuttgart all have strong dedicated vegan scenes. Munich in particular has Max Pett, Bodhi, and Prinz Myshkin. Bavaria and rural areas outside the cities are more traditional and meat-heavy - Schweinshaxe, Bratwurst, and Käsespätzle country. Even there, you will find a Kaufland or Edeka within reach, and most bakeries stock at least one vegan bread. Just do not expect a vegan-friendly menu at a village Gasthof without calling ahead.',
  ],
  phrases: [
    { english: 'Is this vegan?', native: 'Ist das vegan?', pronunciation: 'Ist dass veh-GAHN?' },
    { english: 'I am vegan', native: 'Ich bin Veganer (m) / Veganerin (f)', pronunciation: 'Ikh bin veh-GAH-ner / veh-GAH-ner-in' },
    { english: 'No milk, cheese, eggs, honey please', native: 'Ohne Milch, Käse, Eier, Honig bitte', pronunciation: 'OH-neh milkh, KAY-zeh, EYE-er, HOH-nikh BIT-teh' },
    { english: 'What is vegan here?', native: 'Was ist hier vegan?', pronunciation: 'Vass ist heer veh-GAHN?' },
    { english: 'Does this contain animal ingredients?', native: 'Enthält das tierische Zutaten?', pronunciation: 'Ent-HELT dass TEER-ish-eh TSOO-tah-ten?' },
    { english: 'Can you make this vegan?', native: 'Können Sie das vegan machen?', pronunciation: 'KUR-nen zee dass veh-GAHN MAKH-en?' },
    { english: 'I cannot eat milk / eggs', native: 'Ich vertrage keine Milch / kein Ei', pronunciation: 'Ikh fer-TRAH-geh KY-neh milkh / kyne eye' },
    { english: 'Plant-based', native: 'Pflanzlich', pronunciation: 'PFLANTS-likh' },
    { english: 'Without cream / butter', native: 'Ohne Sahne / Butter', pronunciation: 'OH-neh ZAH-neh / BOO-ter' },
    { english: 'Oat milk or soy milk?', native: 'Hafermilch oder Sojamilch?', pronunciation: 'HAH-fer-milkh OH-der ZOH-ya-milkh?' },
  ],
  dishes: {
    vegan: [
      { name: 'Linseneintopf', nativeName: 'Linseneintopf', status: 'usually-vegan', note: 'Lentil stew. Traditionally made with sausage or bacon but a vegan version is common in cafes and canteens - confirm.' },
      { name: 'Kürbiscremesuppe', nativeName: 'Kürbiscremesuppe', status: 'ask', note: 'Pumpkin cream soup. Often vegan when made with coconut milk but frequently finished with Sahne (cream) or butter - ask.' },
      { name: 'Currywurst (vegan)', nativeName: 'Vegane Currywurst', status: 'vegan', note: 'The vegan version is widely available in Berlin and beyond - Vincent Vegan, Curry 36, and most Imbiss stands now offer it.' },
      { name: 'Vegan Döner', nativeName: 'Veganer Döner', status: 'vegan', note: 'Huge in Berlin. Seitan or soy-based döner with the full salad, sauce, and bread treatment. Kreuzberg and Neukölln are saturated with options.' },
      { name: 'Brezel (Pretzel)', nativeName: 'Brezel', status: 'usually-vegan', note: 'Most industrial pretzels are vegan (flour, water, yeast, lye, salt). Watch for lard or butter in pretzel dough at small traditional Bavarian bakeries.' },
      { name: 'Kartoffelsalat', nativeName: 'Kartoffelsalat', status: 'ask', note: 'German potato salad varies massively by region. Northern (Berlin/Hamburg) versions usually have mayo (often egg-based). Southern (Bavarian/Swabian) versions are vinegar-and-oil and often vegan. Always ask.' },
      { name: 'Vegan Schnitzel', nativeName: 'Veganes Schnitzel', status: 'vegan', note: 'Widely available at Swing Kitchen and most modern German restaurants. The original is breaded in egg - the vegan version uses plant milk and is clearly labelled.' },
    ],
    ask: [
      { name: 'Brezel from small bakeries', nativeName: 'Brezel', status: 'ask', note: 'Industrial chain bakery pretzels are usually vegan; traditional Bavarian bakeries sometimes brush with butter or add lard. Ask.' },
      { name: 'Spätzle', nativeName: 'Spätzle', status: 'ask', note: 'Egg pasta by tradition. A vegan version (without egg) exists at vegan-aware restaurants - ask for "vegane Spätzle."' },
      { name: 'Knödel', nativeName: 'Knödel', status: 'ask', note: 'Potato or bread dumplings. Sometimes vegan, sometimes bound with egg. Ask before ordering.' },
      { name: 'Apfelstrudel', nativeName: 'Apfelstrudel', status: 'ask', note: 'Some bakeries use a butter-laminated pastry; others use a lean dough. The filling is usually fine (apples, raisins, cinnamon, sometimes rum). Ask about the dough and any cream on the side.' },
      { name: 'Kartoffelsalat', nativeName: 'Kartoffelsalat', status: 'ask', note: 'Mayo-based (likely contains egg) or vinegar-based (usually vegan). Regional - always confirm.' },
      { name: 'Most cakes (Sahnetorte etc.)', nativeName: 'Kuchen, Sahnetorte', status: 'ask', note: 'Traditional German cakes are cream-and-butter heavy. Vegan bakeries (Brammibal\'s, Ohlala Vegan Patisserie) exist in major cities - seek them out.' },
    ],
    avoid: [
      { name: 'Bratwurst', nativeName: 'Bratwurst', status: 'avoid', note: 'Pork sausage. The vegan version exists separately ("vegane Bratwurst") and is widely available - but the traditional dish is not veganisable.' },
      { name: 'Schweinshaxe', nativeName: 'Schweinshaxe', status: 'avoid', note: 'Roast pork knuckle. Bavarian staple. Not adaptable.' },
      { name: 'Schwarzwälder Kirschtorte', nativeName: 'Schwarzwälder Kirschtorte', status: 'avoid', note: 'Black Forest cake - cream, butter, eggs throughout. Vegan versions exist at dedicated vegan bakeries only.' },
      { name: 'Käsespätzle', nativeName: 'Käsespätzle', status: 'avoid', note: 'Egg pasta plus cheese plus fried onions. Cheese is the dish. Vegan versions exist at vegan-aware restaurants.' },
      { name: 'Sauerbraten', nativeName: 'Sauerbraten', status: 'avoid', note: 'Marinated braised beef. Not adaptable.' },
      { name: 'Eisbein', nativeName: 'Eisbein', status: 'avoid', note: 'Boiled or pickled pork knuckle. North German classic. Not adaptable.' },
      { name: 'Maultaschen', nativeName: 'Maultaschen', status: 'avoid', note: 'Swabian filled pasta - usually meat and egg pasta. A vegetarian (spinach) version exists but the dough still typically contains egg. Vegan Maultaschen are now sold by some supermarket brands (check the V-Label).' },
    ],
  },
  hiddenIngredients: [
    'Gelatine in cake glazes (Tortenguss) and fruit toppings on supermarket pastries - check the label.',
    'Milk powder (Milchpulver) in pretzels and breads from chain bakeries - especially supermarket bake-off.',
    'Sahne (cream) in many soups labelled "cremig" or "Creme" - ask "ohne Sahne."',
    'Butter (Butter) brushed onto pretzel dough or laminated into pastry at small Bavarian bakeries.',
    'Fish gelatin in some yogurt-style desserts and fruit gummies - check ingredient lists.',
    'L-Cysteine (E920) in some mass-produced bread doughs - usually from duck feathers. Rare in vegan-certified products but worth knowing.',
    'Honey (Honig) in some mustards, salad dressings, and breakfast pastries.',
  ],
  tips: [
    'Download Plants Pack or HappyCow before a Berlin trip - between them you have over a thousand listings in the city alone, more than any other capital in Europe.',
    'Veganz operates 100% vegan supermarkets in Berlin, Hamburg, Munich, Frankfurt, and Cologne. Worth a visit even if you are not shopping - it is a useful snapshot of what the vegan grocery market actually looks like.',
    'Rewe, Edeka, Lidl, Aldi, and Kaufland all carry serious vegan ranges. The V-Label on packaging is third-party audited and reliable - trust it.',
    'Berlin is the densest city for vegan options anywhere in Europe. Even kebab shops do vegan döner. You basically do not need to plan meals.',
    'Bavaria and rural areas need slightly more planning. Find the nearest Kaufland or Edeka for groceries, and check Plants Pack for the city before heading into smaller towns.',
    'Bakeries everywhere stock at least one vegan bread - look for "vegan" labelled loaves. Roggenbrot (rye bread) and most Vollkornbrot (wholegrain) are usually vegan by default.',
    '"Pflanzlich" (plant-based) labelling on menus and packaging is reliable in Germany - it is used precisely, not as marketing fluff.',
    'ProVeg International runs the V-Label scheme and certifies restaurants - a V-Label vegan stamp on a menu item is the strongest restaurant-level signal you will find anywhere in Europe.',
  ],
  relatedTopics: ['cheese', 'bread', 'e-codes', 'vegan-vs-vegetarian'],
  updatedAt: '2026-05-29',
}
