import type { TravelGuide } from '../types'

export const greeceGuide: TravelGuide = {
  countrySlug: 'greece',
  countryName: 'Greece',
  metaTitle: 'How to eat vegan in Greece — phrasebook & dish guide | Plants Pack',
  metaDescription: 'Greek Orthodox fasting tradition produced some of Europe\'s best vegan food: lathera (oil-cooked) vegetable dishes, legume stews, fava, gigantes. Phrasebook + dish guide.',
  vegFriendliness: 4,
  vegFriendlinessNote: 'One of Europe\'s easiest vegan countries thanks to Orthodox fasting (nistisimo) cuisine. Many traditional dishes are vegan by religious tradition; look for "nistisimo" on menus.',
  tldr: 'Greece is much easier than expected for vegans because of nistisimo - the Orthodox Christian fasting cuisine that excludes all animal products including dairy and eggs for ~180 days a year. Traditional lathera (vegetables cooked in olive oil), legume stews, fava, dolmades, and many starters are vegan by tradition. The phrase to know: "Eimai vegan, nistevo" (I am vegan, I fast).',
  intro: [
    'Greek cuisine has a deep plant-based tradition because of **nistisimo** - the Orthodox Christian fasting practice that excludes meat, fish, dairy, and eggs for ~180 days a year (Lent, Wednesdays and Fridays year-round for the strict, and major fasts). Centuries of cooking vegan-friendly food for religious reasons mean traditional Greek menus have many naturally vegan dishes - often the best of the cuisine.',
    '**Lathera** ("oily ones") are vegetable dishes braised in olive oil, tomatoes, and herbs - fasolakia (green beans), bamies (okra), arakas (peas), spanakorizo (spinach rice). **Legume stews** are everywhere: gigantes plaki (giant beans baked with tomato), fakes (lentil soup), revithia (chickpea soup). **Mezze starters** are often vegan: dolmades (stuffed vine leaves - check for meat), fava (split-pea purée), melitzanosalata (eggplant dip), htipiti without feta.',
    'The traps are predictable. **Feta** is everywhere - on salads, in pies, sprinkled on top. **Yogurt** comes with many dishes by default. **Honey** is in baklava, loukoumades, and many sweets. **Egg** is in some moussaka versions and most baking. **Fish** is in salade niçoise-style starters and on most Aegean menus.',
    'Greek waiters are generally familiar with vegans now (especially in tourist areas). The faster route is sometimes to invoke fasting: "Nistevo" (I am fasting) clicks instantly with older Greeks and gets you to the right menu items. Combining "Eimai vegan" (I am vegan) with "nistevo" covers both vocabulary gaps.',
    'Major vegan-friendly cities: Athens (Veganaki, Avocado, Mama Tierra), Thessaloniki (Roots, Lola), Crete - especially Heraklion and Chania (Karavokyrhs, Salis), and the bigger islands (Mykonos, Santorini, Naxos all have at least one dedicated vegan spot).',
  ],
  phrases: [
    { english: 'I am vegan', native: 'Είμαι vegan / Είμαι βίγκαν', pronunciation: 'EE-meh VEE-gan' },
    { english: 'I fast (Orthodox)', native: 'Νηστεύω', pronunciation: 'Nee-STEH-vo' },
    { english: 'Do you have fasting dishes?', native: 'Έχετε νηστίσιμα φαγητά;', pronunciation: 'EH-heh-teh nee-STEE-see-ma fah-yee-TAH?' },
    { english: 'Without cheese / feta', native: 'Χωρίς τυρί / φέτα', pronunciation: 'Ho-REES tee-REE / FEH-ta' },
    { english: 'Without yogurt', native: 'Χωρίς γιαούρτι', pronunciation: 'Ho-REES yia-OUR-ti' },
    { english: 'Without honey', native: 'Χωρίς μέλι', pronunciation: 'Ho-REES MEH-lee' },
    { english: 'Without egg', native: 'Χωρίς αυγό', pronunciation: 'Ho-REES av-GO' },
    { english: 'Thank you', native: 'Ευχαριστώ', pronunciation: 'Ef-ha-ree-STO' },
  ],
  dishes: {
    vegan: [
      { name: 'Fava (yellow split-pea purée)', nativeName: 'Φάβα', status: 'vegan', note: 'Santorini specialty - silky split-pea purée with olive oil and capers. Often served as a starter. Vegan by tradition.' },
      { name: 'Gigantes plaki (giant baked beans)', nativeName: 'Γίγαντες πλακί', status: 'vegan', note: 'Large white beans baked in tomato sauce with herbs. Comforting and reliable.' },
      { name: 'Fasolakia (green beans in oil)', nativeName: 'Φασολάκια λαδερά', status: 'vegan', note: 'Green beans braised in tomato and olive oil. A lathera classic.' },
      { name: 'Bamies (okra stew)', nativeName: 'Μπάμιες', status: 'vegan', note: 'Okra braised in tomato and olive oil.' },
      { name: 'Spanakorizo (spinach rice)', nativeName: 'Σπανακόρυζο', status: 'vegan', note: 'Spinach and rice with herbs, lemon, olive oil. Confirm no feta.' },
      { name: 'Fakes (lentil soup)', nativeName: 'Φακές', status: 'vegan', note: 'Traditional Greek lentil soup with tomato, olive oil, herbs. Reliably vegan.' },
      { name: 'Revithia (chickpea soup)', nativeName: 'Ρεβίθια', status: 'vegan', note: 'Slow-cooked chickpeas with lemon and olive oil.' },
      { name: 'Briam (Greek ratatouille)', nativeName: 'Μπριάμ', status: 'vegan', note: 'Roasted mixed vegetables - potatoes, zucchini, eggplant, tomatoes.' },
      { name: 'Melitzanosalata (eggplant dip)', nativeName: 'Μελιτζανοσαλάτα', status: 'usually-vegan', note: 'Smoky roasted eggplant dip. Most versions are vegan; some add yogurt - ask "horis yiaourti."' },
      { name: 'Horiatiki salad (no feta)', nativeName: 'Χωριάτικη χωρίς φέτα', status: 'vegan', note: 'Greek salad without the feta. Tomatoes, cucumber, onion, olives, oregano, olive oil. Ask "horis feta."' },
      { name: 'Dolmades (stuffed vine leaves)', nativeName: 'Ντολμάδες γιαλαντζί', status: 'usually-vegan', note: '"Gialantzi" = vegetarian/lying = vegan version with rice and herbs. Stuffed-with-meat version exists - confirm.' },
    ],
    ask: [
      { name: 'Tzatziki', nativeName: 'Τζατζίκι', status: 'ask', note: 'Yogurt-based - not vegan in traditional form. Some vegan restaurants now make soy or coconut yogurt versions.' },
      { name: 'Spanakopita / hortopita', nativeName: 'Σπανακόπιτα / Χορτόπιτα', status: 'ask', note: 'Spinach pie. Traditional recipe uses feta and eggs - hortopita (greens pie) is sometimes vegan during fasting. Ask "nistisimo?"' },
      { name: 'Moussaka', nativeName: 'Μουσακάς', status: 'ask', note: 'Almost always contains meat AND béchamel. Vegan versions exist in dedicated vegan restaurants.' },
      { name: 'Stuffed peppers / tomatoes (yemista)', nativeName: 'Γεμιστά', status: 'ask', note: '"Orfana" (orphan) yemista - meat-free version is common during fasting. Ask "yemista nistisima?"' },
      { name: 'Bread', nativeName: 'Ψωμί', status: 'ask', note: 'Most Greek bread is vegan but some festival breads (tsoureki, vasilopita) contain egg and milk.' },
    ],
    avoid: [
      { name: 'Souvlaki, gyros', nativeName: 'Σουβλάκι / Γύρος', status: 'avoid', note: 'Meat. Vegan gyros (soy-based) exist in dedicated vegan spots.' },
      { name: 'Greek salad with feta', nativeName: 'Χωριάτικη με φέτα', status: 'avoid', note: 'Order "horis feta" (without feta) and it becomes a great vegan salad.' },
      { name: 'Tiropita (cheese pie)', nativeName: 'Τυρόπιτα', status: 'avoid', note: 'Cheese is the whole point of the dish.' },
      { name: 'Baklava, loukoumades, kataifi', nativeName: 'Μπακλαβάς / Λουκουμάδες / Καταΐφι', status: 'avoid', note: 'Honey-based syrup. Loukoumades sometimes have a non-honey syrup version - check.' },
      { name: 'Yiaourti me meli (yogurt with honey)', nativeName: 'Γιαούρτι με μέλι', status: 'avoid', note: 'Yogurt + honey. Vegan versions exist with plant yogurt and agave - ask.' },
    ],
  },
  hiddenIngredients: [
    'Feta cheese - sprinkled on top of many "vegetable" dishes by default. Order "horis feta" to be safe.',
    'Yogurt (yiaourti) - in tzatziki, on top of moussaka and many baked dishes, in some salad dressings.',
    'Honey - in most Greek desserts, in some salad dressings, in marinades for greens.',
    'Egg - in some moussaka recipes, in pita and pastry doughs (phyllo is usually vegan; tsoureki and brioche-style breads are not).',
    'Fish - in some appetiser pastes (tarama) and in many island menus where seafood dominates.',
    'Olive oil note: NOT a concern - Greek olive oil is universally vegan and used generously. This is one of the joys of Greek food.',
  ],
  tips: [
    '**The magic word is "nistisimo"** (fasting / Lenten food). Many tavernas have a "nistisimo" section, especially during Lent (40 days before Easter), during the Dormition fast (mid-August), and on Wednesdays and Fridays year-round.',
    '"Eimai vegan, nistevo" (I am vegan, I fast) communicates the request in terms older Greeks immediately understand.',
    'Lathera dishes (oil-cooked vegetables) are essentially vegan by nature - look for the "lathera" section on traditional menus.',
    'Greek olive oil is incredible and used generously in vegan cooking - this is part of why Greek vegan food is so good.',
    'Loukoumades (Greek doughnuts) traditionally use honey syrup but some vegan-aware places offer them with sugar syrup or agave - ask before assuming.',
    'Greek coffee (ellinikos) is vegan; frappé is usually with milk powder unless ordered "sketos" (plain) or with plant milk in newer cafés.',
    'Island travel: Mediterranean islands are easier than expected because tomato, olive oil, beans, and herbs are the cuisine foundation. Smaller islands may have fewer options but the traditional ones are mostly vegan.',
    'Plants Pack covers the main Greek cities and tourist islands; check before booking accommodation in smaller spots.',
  ],
  relatedTopics: ['wine'],
  updatedAt: '2026-05-22',
}
