import type { TravelGuide } from '../types'

export const italyGuide: TravelGuide = {
  countrySlug: 'italy',
  countryName: 'Italy',
  metaTitle: 'How to eat vegan in Italy — phrasebook & dish guide | PlantsPack',
  metaDescription: 'Italy is easier than people think for vegans: pasta, pizza, beans, vegetables are everywhere. The catch is the hidden parmesan, lard in focaccia, and egg-pasta. A practical guide.',
  vegFriendliness: 4,
  vegFriendlinessNote: 'Easier than reputation suggests. Vegetables, beans, and grain dishes are central to Italian cuisine. Watch for hidden cheese, anchovies in pasta sauces, and egg pasta.',
  tldr: 'Italy is genuinely vegan-friendly if you know what to ask. Most pizza dough, dry pasta, beans, and antipasti are vegan. The hidden traps are parmesan in places you would not expect (risotto, pasta water, soup), anchovies in puttanesca and some salads, lard in some breads, and egg in fresh pasta. The phrase "senza formaggio, senza burro, senza uova" (without cheese, butter, eggs) gets you most of the way.',
  intro: [
    'Italy has one of the best vegan baselines in Europe because the cuisine is built on vegetables, legumes, grains, and olive oil. Pasta e fagioli (pasta and beans), ribollita (Tuscan vegetable bread soup), minestrone, pasta al pomodoro, pizza marinara, focaccia, polenta with mushrooms - all naturally vegan or trivially veganisable.',
    'The challenges are specific and predictable. **Fresh pasta** (tagliatelle, ravioli, tortellini) almost always contains egg - dry pasta (spaghetti, penne, rigatoni) is just durum wheat and water. **Parmigiano-Reggiano and Pecorino** hide in places you would not expect: stirred into risotto at the end, in the pasta cooking water, in soups, sprinkled over salads. **Lard** is in some traditional breads and focaccia (especially in central Italy). **Anchovies** appear in pasta puttanesca, some pizzas, salade niçoise, and bagna cauda. **Egg** is in carbonara and many filled pastas.',
    'Major cities have growing dedicated vegan scenes. Rome (Romeow Cat Bistrot, Buddy), Milan (Soulgreen, Lo Vegan), Florence (Brac, Universo Vegano), Bologna (Botanica Lab Cucina), and Naples (Un Sorriso Integrale) all have multiple solid options. Smaller cities and towns rely more on adapting traditional dishes, which is usually easy if you ask.',
    'Italians are generally helpful about dietary restrictions if you communicate clearly. "Sono vegano" (I am vegan) plus a short list of exclusions works better than expecting them to know what "vegan" means by default. Older waiters in smaller towns may not be familiar with the word - leading with the exclusions is safer.',
  ],
  phrases: [
    { english: 'I am vegan', native: 'Sono vegano (m) / vegana (f)', pronunciation: 'SOH-no veh-GAH-no / veh-GAH-na' },
    { english: 'Without cheese, butter, eggs', native: 'Senza formaggio, burro, uova', pronunciation: 'SEN-tsa for-MAH-djo, BOOR-ro, WOH-va' },
    { english: 'Is there meat or fish in this?', native: 'C\'è carne o pesce in questo?', pronunciation: 'Cheh KAR-neh oh PEH-sheh in KWES-to?' },
    { english: 'Does this contain animal products?', native: 'Contiene prodotti animali?', pronunciation: 'Con-tee-EH-neh proh-DOT-tee a-nee-MA-lee?' },
    { english: 'Is the pasta egg-free?', native: 'La pasta è senza uova?', pronunciation: 'La PAS-ta eh SEN-tsa WOH-va?' },
    { english: 'A pizza marinara, please (no cheese)', native: 'Una pizza marinara, per favore', pronunciation: 'OO-na PEET-tsa ma-ree-NAH-ra, per fah-VOH-reh' },
    { english: 'Thank you', native: 'Grazie', pronunciation: 'GRAH-tsee-eh' },
  ],
  dishes: {
    vegan: [
      { name: 'Pizza marinara', nativeName: 'Pizza marinara', status: 'vegan', note: 'Classic Naples-style: dough, tomato, garlic, oregano, olive oil. No cheese by definition.' },
      { name: 'Pasta al pomodoro', nativeName: 'Pasta al pomodoro', status: 'vegan', note: 'Dry pasta with tomato sauce. Almost always vegan - ask for no cheese on top.' },
      { name: 'Pasta aglio e olio', nativeName: 'Pasta aglio, olio e peperoncino', status: 'vegan', note: 'Garlic, olive oil, chilli. Naturally vegan.' },
      { name: 'Pasta e fagioli', nativeName: 'Pasta e fagioli', status: 'vegan', note: 'Pasta and bean soup. Traditional, hearty, almost always vegan (some recipes use pancetta - ask).' },
      { name: 'Minestrone', nativeName: 'Minestrone', status: 'usually-vegan', note: 'Vegetable soup. Usually vegan. Some regions add parmesan rind for flavour - ask "senza formaggio".' },
      { name: 'Ribollita', nativeName: 'Ribollita', status: 'vegan', note: 'Tuscan vegetable + bean + bread soup. Vegan by tradition.' },
      { name: 'Bruschetta al pomodoro', nativeName: 'Bruschetta al pomodoro', status: 'vegan', note: 'Toasted bread with tomato, garlic, basil, olive oil. Classic vegan starter.' },
      { name: 'Insalata mista (mixed salad)', nativeName: 'Insalata mista', status: 'usually-vegan', note: 'Plain mixed salad. Vegan if served without cheese or tuna - confirm.' },
      { name: 'Caponata', nativeName: 'Caponata', status: 'vegan', note: 'Sicilian sweet-and-sour eggplant. Vegan.' },
      { name: 'Grissini, taralli', nativeName: 'Grissini, taralli', status: 'usually-vegan', note: 'Bread sticks and savoury rings. Usually vegan but some include lard - check.' },
    ],
    ask: [
      { name: 'Risotto', nativeName: 'Risotto', status: 'ask', note: 'Almost always finished with butter and parmesan. Ask for "senza burro e formaggio" or pick a vegan-aware restaurant.' },
      { name: 'Fresh pasta (tagliatelle, ravioli, tortellini)', nativeName: 'Pasta fresca', status: 'ask', note: 'Fresh pasta is usually made with egg. Dry pasta is fine. Ask if not sure.' },
      { name: 'Focaccia', nativeName: 'Focaccia', status: 'ask', note: 'Often vegan in Liguria; sometimes contains lard or cheese elsewhere. Ask before ordering.' },
      { name: 'Pesto', nativeName: 'Pesto', status: 'ask', note: 'Traditional pesto has parmesan and pecorino. Some restaurants now do "pesto senza formaggio" - just ask.' },
      { name: 'Bread basket', nativeName: 'Pane', status: 'ask', note: 'Plain Italian bread is usually vegan but some regional breads use lard or milk. Ask.' },
      { name: 'Bean and vegetable side dishes (contorni)', nativeName: 'Contorni di verdure', status: 'ask', note: 'Often dressed with olive oil and lemon (vegan). Some are cooked in butter or with parmesan - ask.' },
    ],
    avoid: [
      { name: 'Pasta carbonara', nativeName: 'Pasta carbonara', status: 'avoid', note: 'Eggs + pecorino + guanciale (cured pork cheek). Impossible to veganise on the fly.' },
      { name: 'Pasta amatriciana', nativeName: 'Pasta amatriciana', status: 'avoid', note: 'Guanciale + pecorino. Sometimes a vegan version is on offer in modern restaurants but rarely traditional.' },
      { name: 'Pasta puttanesca', nativeName: 'Pasta alla puttanesca', status: 'avoid', note: 'Anchovies are central to the sauce. Some places make a fish-free version - explicitly ask.' },
      { name: 'Cacio e pepe', nativeName: 'Cacio e pepe', status: 'avoid', note: 'Pecorino + black pepper. Cheese is the whole dish.' },
      { name: 'Tiramisu, panna cotta, gelato (most)', nativeName: 'Tiramisù, panna cotta, gelato', status: 'avoid', note: 'Mascarpone, cream, dairy gelato. Vegan gelato (sorbetto or specifically "gelato vegano") is increasingly available - ask which flavours are dairy-free.' },
    ],
  },
  hiddenIngredients: [
    'Parmesan / Pecorino in risotto, soups, pasta water, sprinkled on salads. Always specify "senza formaggio."',
    'Lard (strutto) in some focaccia, taralli, and regional breads - especially central and southern Italy.',
    'Eggs in fresh pasta - dry boxed pasta is safe; fresh pasta from the deli case usually is not.',
    'Anchovies in puttanesca sauce, some pizzas, salade niçoise, bagna cauda, and as a flavour base in some braised dishes.',
    'Butter (burro) used to finish many sauces, risottos, and gnocchi - ask "senza burro."',
    'Honey in some salad dressings and on certain cheese boards (you would not be ordering cheese, but worth knowing).',
  ],
  tips: [
    'Use the phrase "Sono vegano, senza carne, pesce, formaggio, burro, uova" (I am vegan: no meat, fish, cheese, butter, eggs). Listing the exclusions is more effective than expecting "vegano" to do all the work.',
    'Pizza marinara is the safe default at any pizzeria - dough, tomato, garlic, oregano, olive oil. Often the cheapest pizza on the menu too.',
    'Look for "Cucina naturale," "vegetariana," or "vegana" signs in shop windows - growing in mid-sized Italian cities.',
    'Dry pasta from any supermarket (Barilla, De Cecco, Garofalo) is almost always vegan. Stock up if you have access to a kitchen.',
    'Aperitivo culture is forgiving - olives, focaccia bites, marinated vegetables. Just verify the focaccia is lard-free.',
    'Vegan gelato exists in most cities now - look for "gelato vegano" or sorbetto. Fruit sorbets are almost always vegan.',
    'PlantsPack and HappyCow both have decent coverage of Italian cities; cross-check both before committing to a trip.',
  ],
  relatedTopics: ['wine'],
  updatedAt: '2026-05-22',
}
