import type { TravelGuide } from '../types'

export const thailandGuide: TravelGuide = {
  countrySlug: 'thailand',
  countryName: 'Thailand',
  metaTitle: 'How to eat vegan in Thailand — phrasebook & dish guide | PlantsPack',
  metaDescription: 'Thailand can be wonderful for vegans if you know about fish sauce, shrimp paste, and oyster sauce. Phrasebook, dish guide, and the magic phrase "jay" for strict Buddhist vegan food.',
  vegFriendliness: 4,
  vegFriendlinessNote: 'Excellent in Bangkok and Chiang Mai with dedicated jay (Buddhist vegan) restaurants. Outside cities, the challenge is fish sauce and shrimp paste in almost every savoury sauce - learn one phrase and you are sorted.',
  tldr: 'Thai cuisine has tons of plant-based dishes by tradition (jay food is Buddhist vegan, more strict than Western vegan). The hidden ingredient is fish sauce (nam pla) which is in almost every savoury Thai dish - plus oyster sauce, shrimp paste, and sometimes egg. The phrase "gin jay" (กินเจ) gets you strict vegan food at any Thai restaurant; "mai sai nam pla" (no fish sauce) handles the rest.',
  intro: [
    'Thailand is a top vegan-friendly destination because of the **jay tradition** - a strict Buddhist plant-based diet observed during the annual Vegetarian Festival and year-round by some practitioners. Jay food excludes all animal products plus strong-smelling vegetables (garlic, onion, leeks). "Aharn jay" (food labelled with the yellow-and-red Chinese characters 齋/เจ) is genuinely vegan and widely available, especially in Chinese-Thai communities and around Buddhist temples.',
    'For tourists, the bigger challenge is that traditional Thai cooking uses **fish sauce (nam pla)** the way Western cooking uses salt - it is in almost every savoury dish. Pad thai, tom yum, green curry, papaya salad, and most stir-fries are seasoned with fish sauce by default. The cook may not even think of it as "an ingredient" - it is just how Thai food is made. The same applies to **oyster sauce** in many stir-fries and **shrimp paste (gapi)** in curry pastes.',
    'The fix: be specific. "Mai sai nam pla, mai sai gapi, mai sai nam man hoy" (no fish sauce, no shrimp paste, no oyster sauce) communicates the actual exclusions. Even better: order jay food when possible - it cuts out the conversation entirely.',
    'Major cities have dedicated vegan restaurants. Bangkok (Veganerie chain, May Veggie Home, Broccoli Revolution, Bonita Café), Chiang Mai (Anchan, Free Bird Café, Eathai Vegetarian House), Phuket (Atsumi Healing Café), Koh Phangan (Karma Kafé). Outside the tourist cities, you mostly rely on adapting dishes or finding the local jay restaurant - there is usually one near any major temple.',
    'Convenience-store options are limited but workable: most 7-Elevens in Thailand stock fresh fruit, plain rice, peanuts, soy milk (Lactasoy and Vitamilk make plant-only options), Pringles in plain flavours, and Oreo cookies.',
  ],
  phrases: [
    { english: 'I am vegan / I eat vegan food', native: 'ผมกินเจ / ฉันกินเจ', pronunciation: 'Pom / Chan gin jay (pom = male speaker, chan = female)' },
    { english: 'No fish sauce', native: 'ไม่ใส่น้ำปลา', pronunciation: 'Mai sai nam pla' },
    { english: 'No oyster sauce', native: 'ไม่ใส่น้ำมันหอย', pronunciation: 'Mai sai nam man hoy' },
    { english: 'No shrimp paste', native: 'ไม่ใส่กะปิ', pronunciation: 'Mai sai gapi' },
    { english: 'No egg', native: 'ไม่ใส่ไข่', pronunciation: 'Mai sai khai' },
    { english: 'No meat, no fish', native: 'ไม่เอาเนื้อ ไม่เอาปลา', pronunciation: 'Mai ao nuea, mai ao pla' },
    { english: 'Is this jay (Buddhist vegan)?', native: 'อันนี้เจไหม?', pronunciation: 'An nee jay mai?' },
    { english: 'Thank you', native: 'ขอบคุณ', pronunciation: 'Khob khun (krap if male / kaa if female)' },
  ],
  dishes: {
    vegan: [
      { name: 'Som tam jay (vegan papaya salad)', nativeName: 'ส้มตำเจ', status: 'vegan', note: 'Papaya salad made without fish sauce and shrimp - common in jay restaurants.' },
      { name: 'Pad pak ruam (mixed vegetable stir-fry)', nativeName: 'ผัดผักรวม', status: 'usually-vegan', note: 'Mixed vegetable stir-fry. Ask "mai sai nam pla mai sai nam man hoy" - very often made vegan on request.' },
      { name: 'Khao soi jay (vegan curry noodle)', nativeName: 'ข้าวซอยเจ', status: 'vegan', note: 'Northern Thai curry noodle, jay version. Find at Chiang Mai jay restaurants.' },
      { name: 'Thai fried rice with vegetables and tofu', nativeName: 'ข้าวผัดผักเต้าหู้', status: 'usually-vegan', note: 'Ask for no egg and no fish sauce. Standard order.' },
      { name: 'Mango sticky rice', nativeName: 'ข้าวเหนียวมะม่วง', status: 'usually-vegan', note: 'Sticky rice + coconut cream + mango. Watch for honey drizzle in tourist versions.' },
      { name: 'Fresh fruit (mango, pineapple, papaya, durian, mangosteen)', nativeName: 'ผลไม้', status: 'vegan', note: 'Street fruit carts are everywhere. Ask for "mai sai nam pla" if buying chilli-salt dipping mix.' },
      { name: 'Coconut water and fresh young coconut', nativeName: 'น้ำมะพร้าว', status: 'vegan', note: 'Reliable, refreshing, ubiquitous.' },
      { name: 'Steamed rice + curry from a jay restaurant', nativeName: 'แกงเจ', status: 'vegan', note: 'Look for the jay flag (yellow with red characters) outside small restaurants - everything inside is vegan.' },
    ],
    ask: [
      { name: 'Pad thai', nativeName: 'ผัดไทย', status: 'ask', note: 'Default contains fish sauce, dried shrimp, egg. Vegan version possible: "pad thai jay" or "mai sai goong haeng, mai sai khai, mai sai nam pla."' },
      { name: 'Green curry / red curry / massaman', nativeName: 'แกงเขียวหวาน / แกงแดง / มัสมั่น', status: 'ask', note: 'Pastes usually contain shrimp paste. Some restaurants now make vegan paste; ask "gaeng jay mee mai" (do you have vegan curry?).' },
      { name: 'Tom yum', nativeName: 'ต้มยำ', status: 'ask', note: 'Almost always has fish sauce and often shrimp. Vegan tom yum is possible to order in vegan-aware places.' },
      { name: 'Tom kha', nativeName: 'ต้มข่า', status: 'ask', note: 'Coconut soup. Usually has fish sauce - ask for the vegan version.' },
      { name: 'Som tam (papaya salad)', nativeName: 'ส้มตำ', status: 'ask', note: 'Standard version contains fish sauce, dried shrimp, sometimes crab. Ask for "som tam jay" or "mai sai pla mai sai goong."' },
      { name: 'Stir-fried noodles (pad see ew, pad kee mao)', nativeName: 'ผัดซีอิ๊ว / ผัดขี้เมา', status: 'ask', note: 'Usually contain oyster sauce, sometimes egg. Ask for vegan version.' },
      { name: 'Spring rolls / summer rolls', nativeName: 'ปอเปี๊ยะ', status: 'ask', note: 'Filling varies - some are vegan, some have shrimp. Ask.' },
    ],
    avoid: [
      { name: 'Tom yum goong, tom yum kung', nativeName: 'ต้มยำกุ้ง', status: 'avoid', note: 'Shrimp-based.' },
      { name: 'Pad krapow moo (pork basil)', nativeName: 'ผัดกะเพราหมู', status: 'avoid', note: 'Pork. Vegan version uses tofu - look for "krapow tofu" or "krapow jay."' },
      { name: 'Anything with "goong" (shrimp), "moo" (pork), "gai" (chicken), "nuea" (beef), "pla" (fish)', nativeName: '', status: 'avoid', note: 'These syllables identify animal products in the dish name.' },
      { name: 'Most desserts with cream or condensed milk', nativeName: '', status: 'avoid', note: 'Cream and condensed milk are common in modern Thai sweets. Mango sticky rice is the safe traditional option.' },
    ],
  },
  hiddenIngredients: [
    'Fish sauce (nam pla, น้ำปลา) - in almost every savoury Thai dish. The single most important phrase to learn is "mai sai nam pla."',
    'Oyster sauce (nam man hoy, น้ำมันหอย) - in many stir-fries and noodle dishes.',
    'Shrimp paste (gapi, กะปิ) - in curry pastes, papaya salad, dipping sauces. Often unmentioned because it dissolves invisibly.',
    'Dried shrimp (goong haeng) - sprinkled into som tam, fried rice, and some noodle dishes.',
    'Egg - added to fried rice, pad thai, and many stir-fries automatically. Specify "mai sai khai."',
    'Condensed milk and evaporated milk - in Thai iced tea, some coffees, modern desserts. Ask "mai sai nom" (no milk).',
    'Honey - in tourist-version mango sticky rice. Traditional version uses sugar.',
  ],
  tips: [
    'The single most useful phrase: "Pom/Chan gin jay" (I eat jay food). Many Thai cooks will then automatically exclude fish sauce, shrimp paste, oyster sauce, eggs, and the five strong-smelling vegetables.',
    'Look for the **yellow flag with red Chinese/Thai characters** (เจ / 齋) on small restaurants. Everything in a jay restaurant is fully vegan by religious rule. Reliable and cheap.',
    'During the **Vegetarian Festival** (Tesagan Gin Je, late September / early October), jay food is everywhere across Thailand - even 7-Eleven runs special jay packaging on instant noodles.',
    'Bangkok has the densest dedicated vegan scene. If transiting, search PlantsPack and HappyCow before leaving the airport.',
    'Coconut milk (gathi) is everywhere and vegan - many curries and desserts are coconut-based and easy to veganise.',
    'Street food: rice with vegetable stir-fry, fresh fruit, coconut, and grilled corn or sweet potato are reliable. Ask one careful question and you usually have a meal in 60 seconds.',
    'Lactasoy and Vitamilk soy milks are sold in every 7-Eleven, in original and chocolate. Coffee shops increasingly stock oat and soy milk in cities.',
  ],
  relatedTopics: [],
  updatedAt: '2026-05-22',
}
