import type { TravelGuide } from '../types'

export const ukGuide: TravelGuide = {
  countrySlug: 'united-kingdom',
  countryName: 'the UK',
  metaTitle: 'How to eat vegan in the UK — phrasebook & dish guide | Plants Pack',
  metaDescription: 'The UK is one of the easiest countries in the world to travel as a vegan. Supermarket vegan ranges are huge, chains have dedicated vegan menus, and Brighton, Bristol, London and Glasgow are dense with options.',
  vegFriendliness: 5,
  vegFriendlinessNote: 'Excellent. The UK has the most developed vegan retail and dining scene in Europe outside Germany.',
  tldr: 'The UK is one of the easiest countries in the world to eat vegan. Supermarket own-brand vegan ranges (Tesco Wicked Kitchen, Sainsbury\'s Plant Pioneers, M&S Plant Kitchen, Asda Plant-Based, Waitrose) are huge. Most high-street chains have dedicated vegan menus, and there are clusters of fully-vegan places in London, Brighton, Bristol, Manchester, Edinburgh, and Glasgow. The traps are traditional pub food: fish & chips fried in beef dripping, Sunday roasts, and cask ales filtered with isinglass.',
  intro: [
    'The UK is arguably the most vegan-developed country in Europe. Veganuary started here in 2014 and now drives the global January vegan pledge. The Vegan Society - which coined the word "vegan" in 1944 - is UK-based, and its Vegan Trademark on packaged products is one of the most reliable certifications in the world.',
    'Supermarket vegan ranges are the strongest in Europe. **Tesco Wicked Kitchen**, **Sainsbury\'s Plant Pioneers**, **M&S Plant Kitchen**, **Asda Plant-Based**, and **Waitrose** all have dedicated vegan lines covering ready meals, sandwiches, cheeses, milks, yoghurts, and frozen mains. Every Tesco Express and Sainsbury\'s Local in central London will have a vegan meal-deal sandwich, a vegan wrap, and at least one vegan ready meal. Travelling through the UK without a kitchen is genuinely easy on supermarket food alone.',
    'On the high street, **Pret a Manger**, **Itsu**, **Wagamama**, **Leon**, **Pizza Express**, **Zizzi**, **Nando\'s**, **Wetherspoons**, and **Greggs** all have explicit vegan menus or marked vegan items. Greggs\' vegan sausage roll and vegan steak bake are road-trip staples (Greggs itself is not 100% vegan but the vegan items are reliable). London is the densest vegan city in Europe outside Berlin - Camden, Hackney, Shoreditch, and Brixton all have multiple fully-vegan restaurants per square mile. Brighton and Bristol are proportionally even denser; Manchester, Edinburgh, Glasgow, and Cardiff have growing scenes.',
    'UK food labelling law distinguishes "vegetarian" and "vegan" on packaging, and major chains follow the same convention on menus. If something is marked **VG** or **Vegan** it has been checked. If it is marked **V** it is vegetarian only and may contain dairy or egg. The Vegan Society Trademark (sunflower logo) on packaged products is the gold standard.',
  ],
  phrases: [
    { english: 'I am vegan', native: 'I am vegan', pronunciation: '-' },
    { english: 'Do you have a vegan menu?', native: 'Do you have a vegan menu?', pronunciation: '-' },
    { english: 'Is this suitable for vegans?', native: 'Is this suitable for vegans?', pronunciation: '-' },
    { english: 'Is this dairy-free?', native: 'Is this dairy-free?', pronunciation: '-' },
    { english: 'Are the chips cooked in vegetable oil?', native: 'Are the chips cooked in vegetable oil?', pronunciation: '-' },
    { english: 'Is the gravy vegan?', native: 'Is the gravy vegan?', pronunciation: '-' },
    { english: 'Is this beer vegan? (no isinglass)', native: 'Is this beer vegan? Does it use isinglass?', pronunciation: '-' },
  ],
  dishes: {
    vegan: [
      { name: 'Jacket potato with baked beans', nativeName: 'Jacket potato with beans', status: 'vegan', note: 'Pub and cafe staple. Skip the butter and cheese - ask for it plain with beans. Naturally vegan.' },
      { name: 'Vegan full English breakfast', nativeName: 'Vegan full English', status: 'usually-vegan', note: 'Most cafes and chains (Wetherspoons, Greggs, Pret) now do a vegan version: vegan sausage, beans, hash browns, mushrooms, tomato, toast.' },
      { name: 'Vegan fish & chips', nativeName: 'Vegan fish & chips', status: 'vegan', note: 'Banana blossom or tofu battered "fish." Sutton & Sons (London), The Vurger Co, and many modern chippies do this - look it up on Plants Pack first.' },
      { name: 'Buddha bowl / grain bowl', nativeName: 'Buddha bowl', status: 'vegan', note: 'Standard cafe and chain offering: grains, roasted veg, hummus, beans. Pret, Leon, Itsu all do reliable versions.' },
      { name: 'Vegan curry house dishes', nativeName: 'Vegan curry', status: 'usually-vegan', note: 'Chana masala, aloo gobi, tarka dal, vegetable biryani, bhindi masala. Always ask "no ghee, no cream" - many curry houses cook with ghee by default.' },
      { name: 'Welsh rarebit (vegan)', nativeName: 'Vegan Welsh rarebit', status: 'vegan', note: 'Toasted bread with vegan cheese sauce and mustard. Increasingly on gastropub menus in Wales and the southwest.' },
      { name: 'Greggs vegan sausage roll', nativeName: 'Vegan sausage roll', status: 'vegan', note: 'Quorn-based, certified by The Vegan Society. Reliable road-trip food at any Greggs.' },
    ],
    ask: [
      { name: 'Chips (fries)', nativeName: 'Chips', status: 'ask', note: 'At traditional chippies, chips are sometimes cooked in beef dripping (tallow). At chains and modern pubs they are almost always vegetable oil. Ask "are the chips cooked in vegetable oil?"' },
      { name: 'Pasta sauces', nativeName: 'Pasta sauce', status: 'ask', note: 'Many "tomato" pasta sauces at pubs are actually cream-based or finished with butter. Ask before ordering.' },
      { name: 'Indian curries', nativeName: 'Curry', status: 'ask', note: 'Ghee (clarified butter) is the default cooking fat at many curry houses, even in "vegetable" dishes. Always specify "no ghee, no cream, no paneer".' },
      { name: 'Pies and pastry', nativeName: 'Pie', status: 'ask', note: 'Pub pies often use lard or butter pastry. Most chain "vegan pies" (Pieminister, Holland\'s) are clearly labelled - but a generic pub pie usually is not vegan.' },
      { name: 'Beer (especially cask ales)', nativeName: 'Beer', status: 'ask', note: 'Some traditional UK cask ales are filtered with isinglass (fish bladder). Brewdog, most modern craft brewers, Guinness (since 2018), and all major lagers are vegan - but a random village pub cask ale might not be. Barnivore is the reference.' },
      { name: 'Pub gravy', nativeName: 'Gravy', status: 'ask', note: 'Default pub gravy is meat-based (beef or chicken stock). Some pubs now do a vegan onion gravy - ask specifically.' },
      { name: 'Yorkshire puddings', nativeName: 'Yorkshire pudding', status: 'ask', note: 'Traditionally made with egg and milk. Vegan versions exist (Aunt Bessie\'s does one) but a homemade pub Yorkshire is not vegan by default.' },
    ],
    avoid: [
      { name: 'Traditional fish & chips', nativeName: 'Fish & chips', status: 'avoid', note: 'Battered in egg and milk, fried in beef dripping at some traditional chippies. Order a dedicated vegan version instead.' },
      { name: 'Sunday roast', nativeName: 'Sunday roast', status: 'avoid', note: 'Everything around the meat is usually non-vegan too: meat gravy, egg Yorkshire pudding, roast potatoes in goose fat, butter-glazed veg. Many gastropubs now offer a vegan roast - book ahead and confirm.' },
      { name: 'Steak & ale pie', nativeName: 'Steak & ale pie', status: 'avoid', note: 'Beef plus butter pastry plus often a non-vegan ale. Traditional pub classic - skip it.' },
      { name: 'Scotch eggs', nativeName: 'Scotch eggs', status: 'avoid', note: 'Boiled egg wrapped in sausage meat. Vegan versions exist at delis (mushroom or jackfruit) - the traditional version does not.' },
      { name: 'Cream tea', nativeName: 'Cream tea', status: 'avoid', note: 'Scones (butter, milk, sometimes egg) with clotted cream and jam. The cream and butter scones are the whole point - traditional cream tea is not veganisable on the fly.' },
      { name: 'Shepherd\'s pie / cottage pie', nativeName: 'Shepherd\'s pie', status: 'avoid', note: 'Lamb (shepherd\'s) or beef (cottage) with butter-and-milk mash. Vegan lentil shepherd\'s pie is common at vegan restaurants - traditional pub version is not vegan.' },
      { name: 'Cornish pasty', nativeName: 'Cornish pasty', status: 'avoid', note: 'Beef and potato in butter or lard pastry. Vegan pasties (Greggs, Cornish Vegan Pasty Co) exist - the traditional protected-name version is not vegan.' },
    ],
  },
  hiddenIngredients: [
    'Ghee in Indian restaurant curries - even "vegetable" dishes are often cooked in ghee by default. Always say "no ghee".',
    'Isinglass (fish bladder) used to clarify some traditional UK cask ales. Brewdog and most modern craft brewers are vegan; check Barnivore for any specific beer.',
    'Beef dripping (tallow) at some traditional fish & chip shops - both for the batter and the chip oil. Chains and modern chippies use vegetable oil.',
    'L-cysteine (E920) in supermarket sliced bread and some bakery products - derived from feathers or hair. Vegan-certified breads avoid this.',
    'Milk powder and whey in supermarket biscuits, crisps, and "plain" crackers - check the allergen line. Cheap own-brand biscuits often have it where you would not expect.',
    'Gelatin in jelly babies, dolly mixtures, wine gums, and most traditional UK sweets. Look for "suitable for vegans" on the back - The Natural Confectionery Co and Candy Kittens do vegan versions.',
  ],
  tips: [
    'Use Plants Pack and HappyCow together - both have strong UK coverage. Plants Pack is denser in London, Brighton, Bristol, and Manchester; HappyCow has wider tail coverage in smaller towns.',
    'Supermarket own-brand vegan ranges are excellent and cheap. Tesco Wicked Kitchen, Sainsbury\'s Plant Pioneers, M&S Plant Kitchen, Asda Plant-Based, and Waitrose all have dedicated vegan sections. A meal-deal vegan sandwich + crisps + drink is around GBP 4.',
    'Major chains (Pret, Itsu, Wagamama, Leon, Pizza Express, Zizzi, Nando\'s, Wetherspoons) all have explicit vegan menus. Wetherspoons in particular is reliable on motorways and in small towns.',
    'Greggs is not 100% vegan but the vegan sausage roll, vegan steak bake, vegan sausage bean & cheeze melt, and vegan glazed ring doughnut are all reliable. Every UK high street has one.',
    'Brighton and Bristol are the densest vegan cities per capita - if you have one day to spend, pick one of these over a generic city visit.',
    'London is the biggest concentration: Camden, Hackney, Shoreditch, Brixton, and Stoke Newington all have multiple fully-vegan places within walking distance. Mildreds, Unity Diner, The Vurger Co, Temple of Seitan, and Black Cat Cafe are dependable.',
    'Scotland and Wales have growing scenes - Glasgow (Mono, The 78, Stereo), Edinburgh (Harmonium, Holy Cow), and Cardiff (Anna Loka, Crumbs) all support a multi-day visit on vegan food alone.',
    'The Vegan Society UK trademark (sunflower logo) on packaged products is the most reliable vegan certification in the world - if you see it, the product has been audited.',
  ],
  relatedTopics: ['cheese', 'bread', 'vegan-vs-vegetarian', 'eggs'],
  updatedAt: '2026-05-29',
}
