import { createAdminClient } from '@/lib/supabase-admin'

/**
 * Create a public feed post that links to a place, authored by `userId`.
 * Shared by the user-driven auto-post route (POST /api/places/[id]/auto-post)
 * and the submission-approval flow (where it posts as the original submitter).
 *
 * `title = placeName` so the post_slug_trigger gives it a clean /post/<slug>.
 * `category:'place'` + `place_id` make PostCard render the linked place card,
 * and `privacy:'public'` keeps it visible in /api/feed/unified.
 *
 * Best-effort: returns the post id or null, never throws into the caller.
 */
export async function createPlacePost(opts: {
  userId: string
  placeId: string
  placeName: string
  content?: string
  images?: string[]
  /** Marks posts generated by an approval so they're identifiable/removable. */
  auto?: boolean
}): Promise<string | null> {
  const { userId, placeId, placeName, content, images = [], auto = false } = opts
  if (!userId || !placeId) return null
  try {
    const admin = createAdminClient()
    const { data, error } = await admin
      .from('posts')
      .insert({
        user_id: userId,
        content: content || `Just added a new vegan spot: ${placeName} 🌱`,
        title: placeName,
        category: 'place',
        place_id: placeId,
        images,
        privacy: 'public',
        tags: auto ? ['auto:submission'] : [],
      })
      .select('id')
      .single()
    if (error) {
      console.error('[createPlacePost]', error.message)
      return null
    }
    return data?.id ?? null
  } catch (e) {
    console.error('[createPlacePost] threw', (e as Error)?.message)
    return null
  }
}
