-- Ensure RLS is enabled on ALL public tables (some may have been missed)
-- This is a safety net — ENABLE ROW LEVEL SECURITY is idempotent

ALTER TABLE IF EXISTS public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.post_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.places ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.favorite_places ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.notification_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.hashtags ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.post_hashtags ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.post_mentions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.post_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.comment_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.post_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.user_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.user_interaction_patterns ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.subscription_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.promotional_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.admin_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.user_blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.user_mutes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.rate_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.contact_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.packs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pack_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pack_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pack_follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.place_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.place_review_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pack_places ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.place_claim_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.place_owners ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.roadmap_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.route_places ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.event_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.recipe_reviews ENABLE ROW LEVEL SECURITY;

-- ═══ Restrict sensitive tables: replace overly permissive SELECT policies ═══

-- favorite_places: only owner should see their favorites (was USING (true))
DROP POLICY IF EXISTS "Favorite places are viewable" ON favorite_places;
DROP POLICY IF EXISTS "favorite_places_select_policy_anon" ON favorite_places;
CREATE POLICY "favorite_places_select_own" ON favorite_places FOR SELECT
  USING (auth.uid() = user_id);
